name: Validate Plugin Tests

on:
  pull_request:
    paths:
      - 'packages/plugin-*/**'

jobs:
  validate-plugin-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build packages (required for tests)
        run: |
          echo "Building packages before running tests..."
          npm run build

      - name: Check Plugin Tests
        run: |
          echo "Checking plugin tests..."
          
          # Find all plugin directories 
          plugins=$(find packages/plugin-* -name "package.json" | xargs dirname)
          
          if [ -z "$plugins" ]; then
            echo "No plugins found, nothing to check"
            exit 0
          fi
          
          failed=false
          
          for plugin in $plugins; do
            name=$(basename "$plugin")
            echo ""
            echo "🔍 Checking $name..."
            
            cd "$plugin"
            
            # Run the tests (with 60 second timeout)
            echo "Running tests..."
            if timeout 60s npm test > /dev/null 2>&1; then
              echo "✅ Tests passed"
            else
              echo "❌ Tests failed or took too long"
              failed=true
            fi
            
            # Check if plugin has core functionality tests
            test_file=$(find tests -name "*.spec.ts" | head -1)
            if [ -f "$test_file" ]; then
              patterns="Core Functionality|Tool Registration|Tool Functionality|API Endpoint|Login Endpoint|OpenAPI Endpoint|Resource Handler|Registration|Functionality"
              if grep -q "$patterns" "$test_file"; then
                echo "✅ Core functionality tests found"
              else
                echo "❌ Missing core functionality tests"
                failed=true
              fi
            else
              echo "❌ No test files found"
              failed=true
            fi
            
            cd - > /dev/null
          done
          
          echo ""
          if [ "$failed" = true ]; then
            echo "❌ Some plugins failed validation"
            echo "See packages/plugin-example/tests/ for examples"
            exit 1
          else
            echo "✅ All plugins passed validation!"
          fi
